// shortForms.js
const shortFormDictionary = {
    'u': 'you',
    'r': 'are',
    'pls': 'please',
    'thx': 'thanks',
    'btw': 'by the way',
    'idk': 'I don’t know',
    'omw': 'on my way',
    'lol': 'laugh out loud',
    'brb': 'be right back',
    'ttyl': 'talk to you later',
    'np': 'no problem',
    'b/c': 'because',
    'msg': 'message',
    'afaik': 'as far as I know',
    'b4': 'before',
    'gr8': 'great',
    'lmk': 'let me know',
    'smh': 'shaking my head',
    'imo': 'in my opinion',
    'fyi': 'for your information',
    'tbh': 'to be honest',
    'rn': 'right now',
    'bc': 'because',
    'bff': 'best friends forever',
    'l8r': 'later',
    'jk': 'just kidding',
    'ily': 'I love you',
    'bday': 'birthday',
    'cya': 'see you',
    'dm': 'direct message',
    'omg': 'oh my god',
    'nvm': 'never mind',
    'tho': 'though',
    'w/e': 'whatever',
    'w/o': 'without',
    'asap': 'as soon as possible',
    'tba': 'to be announced',
    'tbd': 'to be decided',
    'wyd': 'what you doing',
    'g2g': 'got to go',
    'imo': 'in my opinion',
    'irl': 'in real life',
    'atm': 'at the moment',
    'ftw': 'for the win',
    'wth': 'what the heck',
    'icymi': 'in case you missed it',
    'np': 'no problem',
    'wb': 'welcome back',
    'hmu': 'hit me up',
    'imho': 'in my humble opinion',
    'rofl': 'rolling on the floor laughing',
    'idc': 'I don’t care',
    'ikr': 'I know, right',
    'gg': 'good game',
    'xo': 'hugs and kisses',
    'xoxo': 'hugs and kisses',
  };
  
  export default shortFormDictionary;
  